dns:
  fake-ip-filter:
  # youku
  - '+.youku.com'
  - '+.ykimg.com'
  - '+.soku.com'
  - '+.kumiao.com'
  - '+.kuxiaomiao.com'
  - '+.kuxiaomiao.com.cn'
  - '+.kumiao.tv'
  - '+.kuxiaomiao.cn'
  - '+.kuxiaomiao.net'
  - '+.gamenow.club'
  - '+.f2e.tech'
  - '+.wenyupages.com'
  - '+.kanbox.com'
  # autonavi
  - '+.autonavi.com'
  - '+.amap.com'
  - '+.anav.com'
  # taobao 
  - '+.taobao.com'
  - '+.1688.com'
  - '+.xianyu.mobi'
  - '+.alibaba.com'
  - '+.alibabausercontent.com'
  - '+.alibabadns.com'
  - '+.tmall.com'
  # alipay
  - '+.alipay.com'
  - '+.alipay.net'
  - '+.alipayobjects.com'
  - '+.alipaydns.com'
  - '+.alipaydev.com'
  # aliyun
  - '+.alicdn.com'
  - '+.aliyun.com'
  - '+.aliyuncs.com'
  - '+.aliapp.org'
  - '+.alisoft.com'
  - '+.alicloud.com'
  # eleme
  - '+.ele.me'
  - '+.eleme.io'
  - '+.elemecdn.com'
  # dingtalk
  - '+.dingtalk.com'
  - '+.aliwork.com'
