dns:
  fake-ip-filter:
  - '+.baidu.com'
  - '+.shifen.com'
  - '+.bdstatic.com'
  - '+.bdimg.com'
  - '+.hao123.com'
  - '+.hao123img.com'
  - '+.duapp.net'
  - '+.duapp.com'
  - '+.tieba.com'
  - '+.baidupcs.com'
  - '+.jomodns.com'
  - '+.jomodns.net'
  
