dns:
  fake-ip-filter:
  - '+.bilibili.com'
  - '+.biliapi.net'
  - '+.biliapi.com'
  - '+.biligame.com'
  - '+.bilivideo.com'
  - '+.bilivideo.net'
  - '+.b23.tv'
  - '+.acgvideo.com'
  - '+.bilibili.cc'

