proxy-groups:
  - name: "TIKTOK"
    type: select
    proxies: []

# fill proxy-groups.[xxx].proxies with  [.proxies[] | select( .name | test("日本|韩国") ) | .name]
create-proxy-group:
  TIKTOK: "台湾|日本|韩国|美国"

rules:
- DOMAIN-KEYWORD,tiktok,TIKTOK
- DOMAIN-KEYWORD,tiktokv.com,TIKTOK
- DOMAIN-KEYWORD,tiktokcdn.com,TIKTOK
- DOMAIN-KEYWORD,tiktokcdn-us.com,TIKTOK
- DOMAIN-KEYWORD,ibytedtos.com,TIKTOK
- DOMAIN-KEYWORD,ipstatp.com,TIKTOK
- DOMAIN-KEYWORD,bytelb.com,TIKTOK
- DOMAIN-KEYWORD,byteoversea.com,TIKTOK
- DOMAIN-KEYWORD,byteoversea.net,TIKTOK
- DOMAIN-KEYWORD,tik-tokapi.com,TIKTOK
- DOMAIN-KEYWORD,muscdn.com,TIKTOK
- DOMAIN-KEYWORD,musical.ly,TIKTOK
- DOMAIN-KEYWORD,pitaya-clientai.com,TIKTOK
- DOMAIN-KEYWORD,bytegecko,TIKTOK
