dns: 
  fake-ip-filter:
  - '+.zijieapi.com'
  - '+.bytedance.com'
  - '+.toutiao.com'
  - '+.toutiaoimg.com'
  - '+.toutiaocloud.com'
  - '+.toutiaocloud.net'
  - '+.byteimg.com'
  # - '+.amemv.com'
  # - '+.amemv.net'
  - '+.snssdk.com'
  - '+.douyinpic.com'
  - '+.douyinvod.com'
  - '+.idouyinvod.com'
  - '+.douyincdn.com'
  - '+.douyinstatic.com'
  - '+.idouyinstatic.com'
  - '+.iesdouyin.com'
  - '+.iesdouyin.net'
  - '+.huoshan.com'
  - '+.ieshuodong.net'
  - '+.huoshanzhibo.com'
  - '+.huoshanzhibo.net'
  - '+.huoshanvideo.net'
  - '+.huoshanxiaoshipin.net'
  - '+.huoshanvod.com'
  - '+.huoshanlive.com'
  - '+.huoshanstatic.com'
  - '+.huoshanimg.com'
  - '+.duoshan.com'
  - '+.bytegoofy.com'
  - '+.bytescm.com'
  - '+.bytetos.com'
  - '+.bytednsdoc.com'
  - '+.bdurl.net'
  - '+.ecombdapi.com'
  - '+.pglstatp-toutiao.com'
  - '+.pangolin-sdk-toutiao.com'
  - '+.wasu.tv'
  - '+.ixigua.com'
