dns:
  fake-ip-filter:
  - '+.sandai.net'
  - '+.xunlei.com'
  - '+.gigaget.com'
  - '+.kuaipan.cn'
  - '+.xunlei.net'
  - '+.kanimg.com'
  - '+.sjzhushou.com'
  - '+.xbase.cloud'
  - '+.newvr.com'
  - '+.xlpan.com'
  - '+.xycdn.com'
  - '+.xylive.tv'
  - '+.wzhibo.tv'
  - '+.wezhibo.net'
  - '+.wezhibo.tv'
  - '+.wzhibo.net'
  - '+.onethingcloud.cn'
  - '+.xycloud.com'
  - '+.walk-live.com'
  - '+.onething.net'
